version: '3.1'
services:
  app:
    container_name: contenedor1
    image: alpine
    restart: always
    networks:
      red_externa:
        ipv4_address: 192.168.10.10
      red_interna:
        ipv4_address: 192.168.20.10
    hostname: contenedor1

  db:
    container_name: contenedor2
    image: alpine
    restart: always
    networks:
      red_interna:
        ipv4_address: 192.168.20.20
    hostname: contenedor2
networks:
    red_externa:
        ipam:
            config:
              - subnet: 192.168.10.0/24
    red_interna:
        ipam:
            config:
              - subnet: 192.168.20.0/24
